spring.application.name=backtest_platform

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=c##backtest
spring.datasource.password=Backtest
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

token.expiration=3600000
token.secret.key=alexalexalexalexalexalexalexalexalexalexalexalexalexalexalexalex

spring.mvc.pathmatch.matching-strategy=ant_path_matcher